### ISSUE TITLE
DB connection string

### ISSUE THREAD

**Issue by aliasfalse** [Mads-Jakobsen/WarframeNexus#1]
Presently your mongo connection string is in plain text. 
Just for your own security, while it is a LAN-reserved IP, it'd still be safer to move it to either a configuration file or, better yet, a process file for something like PM2

**Comment by Mads-Jakobsen** [comment]
Reverted connections to default, so they should work with the standard mongo/sails configuration.

Turns out I stopped tracking the changes of that file at some point and forgot to remove that setting.
